packages:
    - "apps/*"
    - "libs/auth"
    - "libs/shared/*"
    - "libs/shared/storage/db"
    - "libs/shared/types/"
    - "libs/shared/utils"
    - "libs/middleware"
    - "libs/redis"
    - "libs/events"
    - "libs/sentry"
